# Generated by Django 3.1.5 on 2021-01-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypages', '0002_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
    ]
